FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential libtool libusb-1.0-0-dev librtlsdr-dev rtl-sdr cmake pkg-config

ADD . /repo
WORKDIR /repo/build
RUN cmake ..
RUN make -j8
